_target_: src.model.HiFiGAN
Generator:
  _target_: src.model.HiFiGenerator
  in_channels: 80
  initial_channel: 512
  upsample_rates: [8, 8, 2, 2]
  upsample_kernels: [16, 16, 4, 4]
  resblock_kernels: [3, 7, 11]
  resblock_dilations: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]

MultiPeriodDiscriminator:
  _target_: src.model.MultiPeriodDiscriminator
  periods: [2, 3, 5, 7, 11]

MultiScaleDiscriminator:
  _target_: src.model.MultiScaleDiscriminator