_target_: src.logger.CometMLWriter
project_name: "neural-vocder"
workspace: null
run_name: "testing"
mode: "online"
loss_names: ["g_loss", "d_loss"]
log_checkpoints: False # set to True if you want to log save_dir with checkpoints to W&B
id_length: 32 # length of the run_id
